apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    name: api-config
  namespace: identity-service
data:
  POSTGRES_URL: ""
  JWT_SECRET: ""
  VIACEP_URL: ""
  OPEN_STREET_MAP_URL: ""