@host = http://localhost:3001
@service-prefix = identity-service

# @name register
POST {{host}}/{{service-prefix}}/register
content-type: application/json

{
  "name": "John Doe",
  "email": "john.doe3@example.com",
  "taxvat": "123456789114",
  "password": "john.143",
  "role": "ADMIN",
  "phone": "11999999999",
  "doctorDetails": {
    "crm": 12345671,
    "specialty": "Cardiology"
  },
  "address": {
    "zipcode": "05409-000",
    "street": "Rua Capote Valente",
    "number": 39
  }
}


### 

# @name auth
POST {{host}}/{{service-prefix}}/auth
content-type: application/json

{
    "login": "john.doe3@example.com",
    "password": "john.143"
}

### 

