@host = http://localhost:3001
@service-prefix = hackathon-service

# @name register
POST {{host}}/{{service-prefix}}/register
content-type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "taxvat": "123456678",
  "password": "password",
  "role": "DOCTOR",
  "phone": "11999999999",
  "doctorDetails": {
    "crm": 1234567,
    "specialty": "Cardiology"
  },
  "address": {
    "zipcode": "05409-000",
    "street": "Rua Capote Valente",
    "number": 39
  }
}


### 

# @name auth
POST {{host}}/{{service-prefix}}/auth
content-type: application/json

{
    "login": "john.doe@example.com",
    "password": "password"
}

### 

