# @host = http://localhost:3001
@host = http://57.152.58.46
@service-prefix = hackathon-service

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJzdWIiOiI4NmZlYWI4OS01ODU3LTRjZTctYTgzNC05M2Y2MWIzODg4ODYiLCJpYXQiOjE3MjE4NjUzODksImV4cCI6MTcyMTk1MTc4OX0.JN2bQGYq5WZWlvDfPeISL4am1QWBexs3lC6mhHi0flQ


# @name get-users
GET {{host}}/{{service-prefix}}/users?page=1&pageSize=20
# Authorization: Bearer {{token}}

###

# @name get-user-by-id
GET {{host}}/{{service-prefix}}/users/2eafaccf-d082-4ba9-a5e2-8bf1e240d2f8
# Authorization: Bearer {{token}}

###

# @name get-current-user-infos
GET {{host}}/{{service-prefix}}/users/me
Authorization: Bearer {{token}}

